# Generated by Django 5.0.3 on 2024-03-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='filetype',
            field=models.CharField(max_length=30),
        ),
    ]
