# Generated by Django 5.0.3 on 2024-03-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='semester',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
