# Generated by Django 5.0.3 on 2024-03-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_notes_semester_remove_signup_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
